### ISSUE TITLE
xi:include for overrides?

### ISSUE THREAD

**Issue by grahamc** [tazjin/nixdoc#14]
For certain functions we may want to be able to override them manually. This can be achieved by attempting to include a file with manually written docs from a known path and generating the documentation into a `<xi:fallback>` element.

Open questions:
* Should the entire `<section>` be wrapped, or just its contents?
* Where to put the location reference?

```xml
 <xi:include href="./attrsets.attrByPath.xml"><xi:fallback>
 <section xml:id="function-library-lib.attrsets.attrByPath">
  <title><function>lib.attrset.attrByPath</function></title>

  <subtitle><literal>attrByPath :: [String] -> Any -> AttrSet</literal>
  </subtitle>

  <--! The docs for this function -->

 </section></xi:fallback>
 </xi:include>
```

**Comment by tazjin** [comment]
I think it makes sense to put the include *inside* of the section. This way people can't accidentally misspell the `xml:id`.

As for the location reference, I will do a first version of this that just puts those at the end of the docs. We can find a better fix later.

**Comment by tazjin** [comment]
Pull request #15 implements this.

In this version I opted for this structure:

```xml
<section ...>
  <title> ... </title>
  <xi:include href="./overrides/<functionName>.xml">
    <xi:fallback> ... the normal generated docs </xi:fallback>
  </xi:include>
  <xi:include ... location include />
</section
```

This means concretely:

1. The section and title can not be overridden (to ensure things are uniform and named correctly).
2. The location reference is always at the end.

I've tested it a little bit and it seems to work as intended.
